/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Mantenimiento;

import Clases.MySql;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modificar.frmModificar_Medicamento;
import modificar.frmNuevo_Medicamento;
import modificar.frmReceta;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Leonardo
 */
public class Medicamentos extends javax.swing.JFrame {
public MySql sql=new MySql();
DefaultTableModel modelo;
javax.swing.JDesktopPane jdp;
public int id=0;
frmReceta receta;
    /**
     * Creates new form Medicamentos
     */
     public void an(){
     this.btnnuevo.setEnabled(true);
     }
    public Medicamentos() {
        initComponents();
        this.setTitle("MEDICAMENTOS");
        modelo=(DefaultTableModel)this.jTable1.getModel();
        botones(false);
        llenartabla(); 
        this.btnAR.setVisible(false);
    }
    boolean b=false;
    public Medicamentos(frmReceta receta) {
        initComponents();
        this.setTitle("MEDICAMENTOS");
        b=true;
        modelo=(DefaultTableModel)this.jTable1.getModel();
        botones(false);
        llenartabla();
        activar=true;
        this.btnAR.setEnabled(false);
        this.btnnuevo.setEnabled(false);
        this.receta=receta;
    }
   public void validar(){
   this.setTitle("MEDICAMENTOS");
        b=true;
        modelo=(DefaultTableModel)this.jTable1.getModel();
        botones(false);
        llenartabla();
        activar=true;
        this.btnnuevo.setEnabled(false);
        this.btnAR.setVisible(false);
   }
    void botones(boolean b){
    btneliminar.setEnabled(b);
    btnmodificar.setEnabled(b);
    btncancelar.setEnabled(b);
    }
    public void llenartabla(){
     modelo.setRowCount(0);
     sql.RegistrosTabla("select * from vista_medicamentos",modelo);
    }
    public boolean activar=false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtbuscar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnnuevo = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnAR = new javax.swing.JButton();
        btncancelar2 = new javax.swing.JButton();
        btncancelar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });
        txtbuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtbuscarKeyReleased(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Medicamento", "Cantidad", "Fecha de Vencimiento"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnnuevo.setText("NUEVO");
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");

        btnAR.setBackground(new java.awt.Color(255, 223, 0));
        btnAR.setText("AGREGAR A RECETA");
        btnAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnARActionPerformed(evt);
            }
        });

        btncancelar2.setText("ACTUALIZAR");
        btncancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar2ActionPerformed(evt);
            }
        });

        btncancelar3.setText("REPORTE");
        btncancelar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                    .addComponent(txtbuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnnuevo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmodificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btncancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAR, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnnuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnmodificar)
                        .addGap(18, 18, 18)
                        .addComponent(btneliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar2)
                        .addGap(15, 15, 15)
                        .addComponent(btncancelar3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAR)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarActionPerformed

    private void txtbuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarKeyReleased
        modelo.setRowCount(0);
        sql.RegistrosTabla("call buscar_M('"+txtbuscar.getText()+"')",modelo);  // TODO add your handling code here:
    }//GEN-LAST:event_txtbuscarKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        id=Integer.valueOf(modelo.getValueAt(jTable1.getSelectedRow(),0).toString());
        if(b==false){
        botones(true);}
        
        if(activar==true)
        {
            this.btnAR.setEnabled(true);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        en= "";
        ec= "";
        mm.setdatos();
        mm.Guaradr();
        mm.show();
        /*        String medicamento=JOptionPane.showInputDialog(this,"INGRESE EL NUEVO MEDICAMENTO", "NUEVO MEDICAMENTO", 1);
        int c;
        try {
            c= Integer.parseInt(JOptionPane.showInputDialog(this, "INGRESE LA CANTIDAD", "NUEVO MEDICAMENTO", 1));
        } catch (Exception e) {
            c=0;
        }
        String f=JOptionPane.showInputDialog(this,"INGRESE FECHA DE VENCIMIENTO EN EL FORMATO AÑO-MES-DIA \n EJEMPLO 2020-12-31", "NUEVO MEDICAMENTO", 1);
        if(c==0 || f.equals("")|| medicamento.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Error dato incorrecto");
        }
        else
        {
            sql.EjecutarConsultas("call insertarmedicamento('"+medicamento+"',"+c+",'"+f+"')");
            llenartabla();
            botones(false);
        }*/

    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        en= jTable1.getValueAt(id-1, 1).toString();
        ec= jTable1.getValueAt(id-1, 2).toString();
        mm.setdatos();
        mm.Modificar();
        mm.show();

        // mm.show();

        /*      String medicamento=JOptionPane.showInputDialog(this,"INGRESE NUEVO NOMBRE", "MODIFICAR MEDICAMENTO", 1);
        int c;
        try {
            c= Integer.parseInt(JOptionPane.showInputDialog(this, "INGRESE LA CANTIDAD", "MODIFICAR  MEDICAMENTO", 1));
        } catch (Exception e) {
            c=0;
        }

        String f=JOptionPane.showInputDialog(this,"INGRESE FECHA DE VENCIMIENTO EN EL FORMATO AÑO-MES-DIA \n EJEMPLO 2020-12-31", "MODIFICAR  MEDICAMENTO", 1);
        if(c==0 || f.equals("")|| medicamento.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Error dato incorrecto");
        }
        else{
            sql.EjecutarConsultas("call update_M("+id+",'"+medicamento+"',"+c+",'"+f+"')");
            llenartabla();
            JOptionPane.showMessageDialog(null, "Modificado con exito");
        }
        id=0;
        botones(false);*/
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed

        sql.EjecutarConsultas("call delete_M("+id+")");
        llenartabla();
        id=0;
        botones(false);
    }//GEN-LAST:event_btneliminarActionPerformed
    public frmModificar_Medicamento mm  = new frmModificar_Medicamento(this);
    public frmNuevo_Medicamento nm;
    public String fecha;
    private void btnARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnARActionPerformed
        // TODO add your handling code here:
        nm = new  frmNuevo_Medicamento(this,receta);
        en= jTable1.getValueAt(id-1, 1).toString();
        ec= jTable1.getValueAt(id-1, 2).toString();
        fecha=jTable1.getValueAt(id-1, 3).toString();
        if(Integer.parseInt(ec)>0)
        {
        nm.medicamento(en);
        nm.llenarcmb(ec);
        nm.show();
        this.btnAR.setEnabled(false);
        }
        else
        {
          JOptionPane.showMessageDialog(null, "Este Medicamento esta agotado");
        }
       
        

    }//GEN-LAST:event_btnARActionPerformed
    public void ar(){
    this.btnAR.setEnabled(true);
    }
    public DefaultTableModel gettabla(){
        return modelo;
    }
    public String en="";
    public String ec="";
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        mm.dispose();
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        mm.dispose();
    }//GEN-LAST:event_formWindowClosing
   
    private void btncancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar2ActionPerformed
        // TODO add your handling code here:
        this.llenartabla();
    }//GEN-LAST:event_btncancelar2ActionPerformed

    private void btncancelar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelar3ActionPerformed
     try{
            sql.conec();
            String url = "C:/temp/Lista_Medicamentos.jasper";            
            JasperReport reporte= (JasperReport)JRLoader.loadObject(url);
            Map parametro=new HashMap();
            
            JasperPrint imp=JasperFillManager.fillReport(reporte, parametro, sql.conexion);
            JasperViewer vista=new JasperViewer(imp,false);
            vista.setVisible(true);
            sql.conexion.close();
        }
        catch(Exception x){
            System.out.println("error: "+x.getMessage().toString());
           
        }
    }//GEN-LAST:event_btncancelar3ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Medicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAR;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btncancelar2;
    private javax.swing.JButton btncancelar3;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
