/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modificar;

import Clases.MySql;
import Clases.validacion;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

public class frmAgregarEmbarazo extends javax.swing.JFrame {

    MySql sql = new MySql();
    validacion va = new validacion();
    boolean cambiar = false;
    String metodo, tabla;
    DefaultTableModel modelo;
    public frmAgregarEmbarazo(String titulo, String eti, String meto, DefaultTableModel mod, String tab) {
        initComponents();
        this.setTitle(titulo.toUpperCase());
        lbletiqueta.setText(eti);
        va.cargarCombos(cmbdia, cmbmes, cmbaño);
        cambiar = true;
        metodo = meto;
        tabla = tab;
        modelo=mod;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbaño = new javax.swing.JComboBox<>();
        cmbmes = new javax.swing.JComboBox<>();
        cmbdia = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        lbletiqueta = new javax.swing.JLabel();
        txtcomotermino = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        cmbaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbaño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbañoItemStateChanged(evt);
            }
        });
        cmbaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbañoActionPerformed(evt);
            }
        });

        cmbmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiempre", "Octubre", "Noviembre", "Diciembre" }));
        cmbmes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmesItemStateChanged(evt);
            }
        });

        cmbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("FECHA:");

        lbletiqueta.setText("COMO TERMINO:");

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btncancelar.setText("CANCELAR");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnguardar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(22, 22, 22)
                            .addComponent(cmbaño, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbmes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cmbdia, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbletiqueta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtcomotermino))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbletiqueta)
                    .addComponent(txtcomotermino, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btnguardar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmbañoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbañoItemStateChanged
        if (cambiar) {
            va.combodia(cmbdia, cmbmes, cmbaño);
        }
    }//GEN-LAST:event_cmbañoItemStateChanged

    private void cmbmesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmesItemStateChanged
        va.combodia(cmbdia, cmbmes, cmbaño);
    }//GEN-LAST:event_cmbmesItemStateChanged

    private void cmbañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbañoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbañoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed

        dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        String co=  txtcomotermino.getText();
        if(!co.isEmpty()){
         sql.EjecutarConsultas(metodo+",'"+va.getfecha(cmbdia, cmbmes, cmbaño)+"','"+co+"')");
         sql.RegistrosTabla(tabla, modelo);
        }  
        this.dispose();
    }//GEN-LAST:event_btnguardarActionPerformed

    public void cargarupdate(String f, String ct, int opc) {
        JComboBox A[] = {cmbaño, cmbmes, cmbdia};
        va.obtenerfecha(f, A);
        txtcomotermino.setText(ct);
        if (opc == 3) {
            btnguardar.setVisible(false);
            btncancelar.setText("CERRAR");
            txtcomotermino.setEditable(false);
            cmbaño.setEditable(false);
            cmbmes.setEditable(false);
            cmbdia.setEditable(false);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JComboBox<String> cmbaño;
    private javax.swing.JComboBox<String> cmbdia;
    private javax.swing.JComboBox<String> cmbmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbletiqueta;
    private javax.swing.JTextField txtcomotermino;
    // End of variables declaration//GEN-END:variables
}
