package Interfaz;


import Clases.MySql;
import Clases.hilo_cola;
import Clases.validacion;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brenedin Enrique
 */
public class cola extends javax.swing.JInternalFrame {
DefaultTableModel model;
    /**
     * Creates new form cola
     */
    public cola(int es, boolean b) {
        initComponents();
        e=es;
        if(e==1){this.setTitle("MEDICO GENERAL");}
        if(e==2){this.setTitle("ODONTOLOGO");}
        if(e==3){this.setTitle("PSICOLOGO");}
        if(e==4){this.setTitle("PRECLINICA");}
        atender.setVisible(b);
        model=(DefaultTableModel)this.jTable1.getModel();
        h= new hilo_cola();
        h.cargar(e, model,this);
        h.start();
        
    }
    String cuentad="";
    String cuentap="";
    int e=0;
    frm_Principal p;
    public cola(String cd, int es, boolean b,frm_Principal pr) {
        initComponents();
        e=es;
        p=pr;
        if(e==1){this.setTitle("MEDICO GENERAL");}
        if(e==2){this.setTitle("ODONTOLOGO");}
        if(e==3){this.setTitle("PSICOLOGO");}
        if(e==4){this.setTitle("PRECLINICA");}
        cuentad=cd;
        atender.setVisible(b);
        model=(DefaultTableModel)this.jTable1.getModel();
        h= new hilo_cola();
        h.cargar(e, model,this);
        h.llenartabla();
        h.start();
        
    }
    hilo_cola h;
    public cola() {
        initComponents();
        
    }
    public void bloquear(boolean b){
    this.atender.setEnabled(b);
    }
    int c=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        atender = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cuenta", "Nombre", "Apellido", "Medico"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(40);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        atender.setText("Atender");
        atender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(atender)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(atender)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atenderActionPerformed
        
        
        cuentap=model.getValueAt(0, 1).toString();
        
        int idp= sql.valor("select buscar_idpaciente("+cuentap+")");
        
        
        if(e==1)
        {
         sql.EjecutarConsultas("call insert_visita(2,"+idp+","+e+",'"+fecha+"')");
         frmConsultaGeneral cg = new frmConsultaGeneral(cuentad,cuentap);
        p.JDP(cg);
        p.ventanas.add(cg);
        cg.setVisible(true);
        }
        if(e==2)
        {
         sql.EjecutarConsultas("call insert_visita(2,"+idp+","+e+",'"+fecha+"')");
         frmConsultaOdonto2 odontologo = new frmConsultaOdonto2(cuentad,cuentap);
        p.JDP(odontologo);
        p.ventanas.add(odontologo);
        odontologo.setVisible(true);
        }
        if(e==3)
        {
        sql.EjecutarConsultas("call insert_visita(2,"+idp+","+e+",'"+fecha+"')");
        frmConsultaPsico psicologo = new frmConsultaPsico(cuentad,cuentap);
        p.JDP(psicologo);
        p.ventanas.add(psicologo);
        psicologo.setVisible(true);
        }
        
        if(e==4)
        {
        sql.EjecutarConsultas("call insert_visita(3,"+idp+","+e+",'"+fecha+"')");
        frmPreclinica1 pre = new frmPreclinica1(cuentad,cuentap);
        p.JDP(pre);
        p.ventanas.add(pre);
        pre.setVisible(true);
        }
    
    }//GEN-LAST:event_atenderActionPerformed
    validacion va=new validacion();
    String fecha= va.getfecha();
    MySql sql = new MySql();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
