package Interfaz;

import Clases.MySql;
import Clases.validacion;
import java.util.Calendar;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Brenedin Enrique
 */
public class frmPreclinica1 extends javax.swing.JInternalFrame {

    Calendar cal = Calendar.getInstance();
    int year = cal.get(Calendar.YEAR);
    MySql sql = new MySql();
    
    public frmPreclinica1() {
        initComponents();
        actualizar();
        cargarCombo();
       
        cambiar = true;
        this.btnguardar.setEnabled(false);
        this.btnModificar.setEnabled(false);
    }
    public frmPreclinica1(String ce, String c) {
        initComponents();
        actualizar();
        cargarCombo();
        cambiar = true;
        this.btnguardar.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.txtNcuenta.setText(c);
        this.ce=ce;
        this.btnguardar.setEnabled(true);
        this.btnModificar.setEnabled(true);
        this.btnbuscar.setEnabled(true);
        //this.btnbuscar.doClick();
        buscar(c);
        
    }
    public void buscar(String cp){
      actualizar();
        l_preclinica();
        
        JTextField A[]= { txtNidentida,txtnombre,txtapellido,
        this.txtdireccion,this.txtcorreo,txttelefono,this.txtprocedencia,
        this.txtnombreEm,this.txttelefonoEm };
        JComboBox B[]={cmbcarrera,cmbsexo,cmbestadocivil};
        JComboBox C[]={cmbaño,cmbmes,cmbdia};
        sql.obtenerfecha("select fecha_nacimiento from persona where nocuenta="+cp, C);
        sql.camposArreglo("call buscar_paciente("+cp+")", A);
        String dia= this.cmbdia.getSelectedItem().toString();
        int mes= this.cmbmes.getSelectedIndex();
        String a= this.cmbaño.getSelectedItem().toString();
        String f=a+"-"+mes+"-"+dia;
        validacion va=new validacion();
        txtEdad.setText(va.obtenerEdad(f));
        
        if(sql.versiesta("call buscar_preclinica("+cp+")")){
        JTextField D[]={this.txtPeso,this.txtTalla,this.txtIMC,this.txtTemperatura,this.txtPulso,this.txtPA};
        sql.camposArreglo("call buscar_preclinica("+cp+")", D);
        this.btnguardar.setEnabled(false);
        this.btnModificar.setEnabled(true);
        this.btnbuscar.setEnabled(false);
     
        }
        else{
        
        this.btnguardar.setEnabled(true);
        this.btnModificar.setEnabled(false);
        this.btnbuscar.setEnabled(false); 
        }
        
    
    
    
    }
    public frmPreclinica1(String ce) {
        initComponents();
        this.ce=ce;
        actualizar();
        cargarCombo();
        cambiar = true;
        this.btnguardar.setEnabled(false);
        this.btnModificar.setEnabled(false);
    }
   
    String cuenta;
    String correo;
    String nombre;
    String apellido;
    String direccion;
    String identidad;
    String carrera;
    String procedencia;
    int sexo;
    int estadoCivil;
    String fechaNacimiento;
    String telefono;
    String telefonoEm;
    String nombreEm;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_Seguro = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtNidentida = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtprocedencia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        txtHora = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtnombre = new javax.swing.JTextField();
        txttelefonoEm = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnombreEm = new javax.swing.JTextField();
        txtNcuenta = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTalla = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        txtIMC = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtTemperatura = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtPA = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtPulso = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        btnbuscar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        cmbcarrera = new javax.swing.JComboBox<>();
        cmbsexo = new javax.swing.JComboBox<>();
        cmbestadocivil = new javax.swing.JComboBox<>();
        cmbaño = new javax.swing.JComboBox<>();
        cmbmes = new javax.swing.JComboBox<>();
        cmbdia = new javax.swing.JComboBox<>();
        txtcorreo = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("PRECLINICA");
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNidentida.setEditable(false);
        txtNidentida.setBackground(new java.awt.Color(255, 223, 0));
        txtNidentida.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNidentida.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtNidentida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNidentidaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNidentida, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 153, 456, 24));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("Carrera:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 189, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("Procedencia:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 225, -1, 24));

        txtprocedencia.setEditable(false);
        txtprocedencia.setBackground(new java.awt.Color(255, 223, 0));
        txtprocedencia.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtprocedencia.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtprocedencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprocedenciaActionPerformed(evt);
            }
        });
        jPanel1.add(txtprocedencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 225, 499, 24));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel10.setText("Sexo:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 260, -1, 24));

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("Estado Civil:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 295, -1, 24));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel12.setText("Fecha de Nacimiento:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 330, -1, 24));

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel18.setText("Hora actual");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 596, -1, -1));

        txtFecha.setEditable(false);
        txtFecha.setBackground(new java.awt.Color(255, 223, 0));
        txtFecha.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtFecha.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 512, 222, 24));

        jPanel2.setBackground(new java.awt.Color(65, 105, 225));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(785, 0, -1, 790));

        txtHora.setEditable(false);
        txtHora.setBackground(new java.awt.Color(255, 223, 0));
        txtHora.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtHora.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraActionPerformed(evt);
            }
        });
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 596, 224, 24));

        jPanel3.setBackground(new java.awt.Color(255, 223, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 83, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(864, 0, -1, 800));

        txtnombre.setEditable(false);
        txtnombre.setBackground(new java.awt.Color(255, 223, 0));
        txtnombre.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtnombre.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 47, 527, 24));

        txttelefonoEm.setEditable(false);
        txttelefonoEm.setBackground(new java.awt.Color(255, 223, 0));
        txttelefonoEm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txttelefonoEm.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txttelefonoEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoEmActionPerformed(evt);
            }
        });
        jPanel1.add(txttelefonoEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 470, 228, 24));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 82, -1, -1));

        txtapellido.setEditable(false);
        txtapellido.setBackground(new java.awt.Color(255, 223, 0));
        txtapellido.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtapellido.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtapellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtapellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 82, 525, 24));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("Dirección:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 117, -1, -1));

        txtdireccion.setEditable(false);
        txtdireccion.setBackground(new java.awt.Color(255, 223, 0));
        txtdireccion.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtdireccion.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 117, 517, 24));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("Número de Identidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 153, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel13.setText("Telefono:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 365, -1, -1));

        txttelefono.setEditable(false);
        txttelefono.setBackground(new java.awt.Color(255, 223, 0));
        txttelefono.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txttelefono.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txttelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 365, 520, 24));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 47, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel14.setText("En caso de emergencia llamar a:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 400, -1, 24));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel15.setText("Nombre:");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 435, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("Número de Cuenta:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, -1));

        txtnombreEm.setEditable(false);
        txtnombreEm.setBackground(new java.awt.Color(255, 223, 0));
        txtnombreEm.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtnombreEm.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtnombreEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreEmActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombreEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 435, 228, 24));

        txtNcuenta.setBackground(new java.awt.Color(255, 223, 0));
        txtNcuenta.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtNcuenta.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtNcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNcuentaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 11, 457, 24));

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel16.setText("Telefono:");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 470, -1, -1));

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel17.setText("Fecha actual");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 516, -1, -1));

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel20.setText("Edad:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, -1, -1));

        txtEdad.setEditable(false);
        txtEdad.setBackground(new java.awt.Color(255, 223, 0));
        txtEdad.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtEdad.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });
        jPanel1.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 650, 100, 24));

        jLabel21.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel21.setText("Peso:");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 650, -1, -1));

        txtPeso.setBackground(new java.awt.Color(255, 223, 0));
        txtPeso.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPeso.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, 100, 24));

        jLabel22.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel22.setText("Kg.");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 650, -1, -1));

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel23.setText("Talla:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 650, -1, -1));

        txtTalla.setBackground(new java.awt.Color(255, 223, 0));
        txtTalla.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtTalla.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtTalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTallaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 650, 100, 24));

        jLabel24.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel24.setText("cm.");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 650, -1, -1));

        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel25.setText("IMC:");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 650, -1, -1));

        txtIMC.setBackground(new java.awt.Color(255, 223, 0));
        txtIMC.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtIMC.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIMCActionPerformed(evt);
            }
        });
        jPanel1.add(txtIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 650, 100, 24));

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel26.setText("Temperatura:");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        txtTemperatura.setBackground(new java.awt.Color(255, 223, 0));
        txtTemperatura.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtTemperatura.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTemperaturaActionPerformed(evt);
            }
        });
        jPanel1.add(txtTemperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, 46, 24));

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel27.setText("°C");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 680, -1, -1));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel28.setText("Presion arterial:");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 680, -1, -1));

        txtPA.setBackground(new java.awt.Color(255, 223, 0));
        txtPA.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPA.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPAActionPerformed(evt);
            }
        });
        jPanel1.add(txtPA, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 680, 42, 24));

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel29.setText("mmHg");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, -1, -1));

        jLabel30.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel30.setText("Pulso: ");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, -1, -1));

        txtPulso.setBackground(new java.awt.Color(255, 223, 0));
        txtPulso.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtPulso.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtPulso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPulsoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPulso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 680, 70, 24));

        jLabel31.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel31.setText("mmHg");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 680, -1, -1));

        jPanel8.setBackground(new java.awt.Color(65, 105, 225));

        btnbuscar.setBackground(new java.awt.Color(255, 223, 0));
        btnbuscar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnbuscar.setText("BUSCAR");
        btnbuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        btnnuevo.setBackground(new java.awt.Color(255, 223, 0));
        btnnuevo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnnuevo.setText("LIMPIAR");
        btnnuevo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnModificar.setBackground(new java.awt.Color(255, 223, 0));
        btnModificar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnguardar.setBackground(new java.awt.Color(255, 223, 0));
        btnguardar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnguardar.setText("GUARDAR");
        btnguardar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 718, 856, 80));

        cmbcarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbcarrera.setEnabled(false);
        jPanel1.add(cmbcarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 189, 163, -1));

        cmbsexo.setBackground(new java.awt.Color(255, 223, 0));
        cmbsexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));
        cmbsexo.setToolTipText("");
        cmbsexo.setEnabled(false);
        cmbsexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbsexoActionPerformed(evt);
            }
        });
        cmbsexo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbsexoKeyPressed(evt);
            }
        });
        jPanel1.add(cmbsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(113, 260, 511, -1));

        cmbestadocivil.setBackground(new java.awt.Color(255, 223, 0));
        cmbestadocivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Union Libre", "Casado", "Divorciado", "Viudo", " " }));
        cmbestadocivil.setToolTipText("");
        cmbestadocivil.setEnabled(false);
        cmbestadocivil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbestadocivilKeyPressed(evt);
            }
        });
        jPanel1.add(cmbestadocivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 286, 467, -1));

        cmbaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbaño.setEnabled(false);
        cmbaño.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbañoItemStateChanged(evt);
            }
        });
        cmbaño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbañoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cmbañoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cmbañoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cmbañoMousePressed(evt);
            }
        });
        cmbaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbañoKeyPressed(evt);
            }
        });
        jPanel1.add(cmbaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 333, 210, -1));

        cmbmes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiempre", "Octubre", "Noviembre", "Diciembre" }));
        cmbmes.setEnabled(false);
        cmbmes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbmesItemStateChanged(evt);
            }
        });
        cmbmes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbmesKeyPressed(evt);
            }
        });
        jPanel1.add(cmbmes, new org.netbeans.lib.awtextra.AbsoluteConstraints(389, 333, 131, -1));

        cmbdia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbdia.setEnabled(false);
        cmbdia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmbdiaKeyPressed(evt);
            }
        });
        jPanel1.add(cmbdia, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 333, 98, -1));

        txtcorreo.setEditable(false);
        txtcorreo.setBackground(new java.awt.Color(255, 223, 0));
        txtcorreo.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        txtcorreo.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 554, 256, 24));

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel19.setText("Correo institucional:");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 558, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 971, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNidentidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNidentidaActionPerformed
     
    }//GEN-LAST:event_txtNidentidaActionPerformed

    private void txtprocedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprocedenciaActionPerformed
        this.cmbsexo.requestFocus();
        this.cmbsexo.showPopup();
    }//GEN-LAST:event_txtprocedenciaActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        this.txtapellido.requestFocus();
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txttelefonoEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoEmActionPerformed
      
    }//GEN-LAST:event_txttelefonoEmActionPerformed

    private void txtapellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtapellidoActionPerformed
        this.txtdireccion.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtapellidoActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        this.txtNidentida.requestFocus();
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txttelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttelefonoActionPerformed
        this.txtnombreEm.requestFocus();
    }//GEN-LAST:event_txttelefonoActionPerformed

    private void txtnombreEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreEmActionPerformed
        this.txttelefonoEm.requestFocus();
    }//GEN-LAST:event_txtnombreEmActionPerformed

    private void txtNcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNcuentaActionPerformed
        txtnombre.requestFocus();
    }//GEN-LAST:event_txtNcuentaActionPerformed
    
    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
        this.btnguardar.setEnabled(false);
        this.btnModificar.setEnabled(false);
        this.btnbuscar.setEnabled(true);
        //this.btncancelar.setEnabled(false); 
        limpiar();
        actualizar();
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        validacion va=new validacion();
        String f= va.getfechahora();
        double peso=0;
        double talla= 0;
        double imc= 0;
        double tem= 0;
        double pulso= 0;
        double pt= 0;
        try {
        
        peso= Double.parseDouble(this.txtPeso.getText());
        talla= Double.parseDouble(this.txtTalla.getText());
        imc= Double.parseDouble(this.txtIMC.getText());
        tem= Double.parseDouble(this.txtTemperatura.getText());
        pulso= Double.parseDouble(this.txtPulso.getText());
        pt= Double.parseDouble(this.txtPA.getText());   
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Dato Incorrecto o Faltan Datos");
        }
        if(peso!=0 && talla!=0 && imc!=0 && tem!=0 && pulso!=0 && pt!=0 )
        {
            sql.EjecutarConsultas("select insertar_preclinica(2,"+ce+","+cuenta+","+peso+","+talla+","+imc+","+tem+","+pulso+","+pt+",'"+f+"')");
             JOptionPane.showMessageDialog(null, "Modificado con Exito");
            
        }
    }//GEN-LAST:event_btnModificarActionPerformed
    String ce;
    
    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
       validacion va=new validacion();
        String f= va.getfechahora();
        double peso=0;
        double talla= 0;
        double imc= 0;
        double tem= 0;
        double pulso= 0;
        double pt= 0;
        try {
        cuenta=(this.txtNcuenta.getText());
        peso= Double.parseDouble(this.txtPeso.getText());
        talla= Double.parseDouble(this.txtTalla.getText());
        imc= Double.parseDouble(this.txtIMC.getText());
        tem= Double.parseDouble(this.txtTemperatura.getText());
        pulso= Double.parseDouble(this.txtPulso.getText());
        pt= Double.parseDouble(this.txtPA.getText());   
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Dato Incorrecto o Faltan Datos");
        }
        if(peso!=0 && talla!=0 && imc!=0 && tem!=0 && pulso!=0 && pt!=0 )
        {
            sql.EjecutarConsultas("select insertar_preclinica(1,"+ce+","+cuenta+","+peso+","+talla+","+imc+","+tem+","+pulso+","+pt+",'"+f+"')");
            JOptionPane.showMessageDialog(null, "Guardado con exito");
        }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void cmbsexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbsexoActionPerformed

    }//GEN-LAST:event_cmbsexoActionPerformed

    private void cmbsexoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbsexoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.cmbestadocivil.requestFocus();
            this.cmbestadocivil.showPopup();
        }
    }//GEN-LAST:event_cmbsexoKeyPressed

    private void cmbestadocivilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbestadocivilKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.cmbaño.requestFocus();
            this.cmbaño.showPopup();
        }
    }//GEN-LAST:event_cmbestadocivilKeyPressed
    boolean cambiar = false;
    private void cmbañoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbañoItemStateChanged
        if (cambiar) {
            combodia();
        }
    }//GEN-LAST:event_cmbañoItemStateChanged
    void combodia() {
        int mes = cmbmes.getSelectedIndex() + 1;
        int año = Integer.valueOf(cmbaño.getSelectedItem().toString());
        cmbdia.removeAllItems();
        if (mes % 2 == 0) {
            if ((mes == 2) && (año % 4 == 0)) {
                for (int i = 1; i <= 29; i++) {
                    cmbdia.addItem(String.valueOf(i));
                }
            } else if (mes == 2) {
                for (int i = 1; i < 29; i++) {
                    cmbdia.addItem(String.valueOf(i));
                }
            } else {
                for (int i = 1; i < 31; i++) {
                    cmbdia.addItem(String.valueOf(i));
                }
            }
        } else {
            for (int i = 1; i <= 31; i++) {
                cmbdia.addItem(String.valueOf(i));
            }
        }
    }
    private void cmbañoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbañoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbañoMouseClicked

    private void cmbañoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbañoMouseEntered

    }//GEN-LAST:event_cmbañoMouseEntered

    private void cmbañoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbañoMouseExited

    }//GEN-LAST:event_cmbañoMouseExited

    private void cmbañoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbañoMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbañoMousePressed

    private void cmbañoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbañoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.cmbmes.requestFocus();
            this.cmbmes.showPopup();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbañoKeyPressed

    private void cmbmesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbmesItemStateChanged
       // combodia();
    }//GEN-LAST:event_cmbmesItemStateChanged

    private void cmbmesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbmesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.cmbdia.requestFocus();
            this.cmbdia.showPopup();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmesKeyPressed

    private void cmbdiaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmbdiaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.txttelefono.requestFocus();

        }        // TODO add your handling code here:
    }//GEN-LAST:event_cmbdiaKeyPressed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        txtnombre.requestFocus();        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        actualizar();
        l_preclinica();
        cuenta=txtNcuenta.getText();
        if(cuenta.equals("")){JOptionPane.showMessageDialog(null, "Ingrese un numero de cuenta");}
        else{
        if(sql.versiesta("call buscar_paciente("+cuenta+")")){
        JTextField A[]= { txtNidentida,txtnombre,txtapellido,
        this.txtdireccion,this.txtcorreo,txttelefono,this.txtprocedencia,
        this.txtnombreEm,this.txttelefonoEm };
        JComboBox B[]={cmbcarrera,cmbsexo,cmbestadocivil};
        JComboBox C[]={cmbaño,cmbmes,cmbdia};
        sql.obtenerfecha("select fecha_nacimiento from persona where nocuenta="+cuenta, C);
        sql.camposArreglo("call buscar_paciente("+cuenta+")", A);
        String dia= this.cmbdia.getSelectedItem().toString();
        int mes= this.cmbmes.getSelectedIndex();
        String a= this.cmbaño.getSelectedItem().toString();
        String f=a+"-"+mes+"-"+dia;
        validacion va=new validacion();
        txtEdad.setText(va.obtenerEdad(f));
        if(sql.versiesta("call buscar_preclinica("+cuenta+")")){
        JTextField D[]={this.txtPeso,this.txtTalla,this.txtIMC,this.txtTemperatura,this.txtPulso,this.txtPA};
        sql.camposArreglo("call buscar_preclinica("+cuenta+")", D);
        this.btnguardar.setEnabled(false);
        this.btnModificar.setEnabled(true);
        this.btnbuscar.setEnabled(false);
        }
        else{
        this.btnguardar.setEnabled(true);
        this.btnModificar.setEnabled(false);
        this.btnbuscar.setEnabled(false); 
        }
        }
        else{
        JOptionPane.showMessageDialog(null, "Numero de cuenta no registrado");
        }
    }
      
        
        // sql.comboArreglo("call buscar_paciente_combo("+cuenta1+")", B);
       
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void txtPulsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPulsoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPulsoActionPerformed

    private void txtTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTemperaturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTemperaturaActionPerformed

    private void txtPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoActionPerformed

    private void txtPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPAActionPerformed

    private void txtIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIMCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIMCActionPerformed

    private void txtTallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTallaActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed
    void actualizar(){
    validacion va=new validacion();
        this.txtFecha.setText(va.getfecha());
        this.txtHora.setText(va.getHora());
    }
    void bloquearBotones(boolean b) {
        //this.btncancelar.setEnabled(!b);
        this.btnbuscar.setEnabled(b);
        this.btnnuevo.setEnabled(b);
        this.btnModificar.setEnabled(b);
    }


    void limpiar() {
        this.txtNcuenta.setText("");
        this.txtcorreo.setText("");
        this.txtdireccion.setText("");
        this.cmbestadocivil.setSelectedIndex(0);
        this.txttelefono.setText("");
        this.txtnombreEm.setText("");
        this.txttelefonoEm.setText("");
        this.txtnombre.setText("");
        this.txtapellido.setText("");
        this.txtNidentida.setText("");
        this.txtprocedencia.setText("");
        l_preclinica();
       
    }
    void l_preclinica(){
        this.txtEdad.setText("");
        this.txtPeso.setText("");
        this.txtPA.setText("");
        this.txtIMC.setText("");
        this.txtTalla.setText("");
        this.txtTemperatura.setText("");
        this.txtPulso.setText("");
    }
   /* void guardar() {
        this.bloquearInmodificable(false);
        this.bloquearModificable(false);
        limpiar();
    }*/
    String getfecha() {
        String dia, mes, año;
        dia = cmbdia.getSelectedItem().toString();
        mes = String.valueOf(cmbmes.getSelectedIndex() + 1);
        año = cmbaño.getSelectedItem().toString();
        if (mes.length() < 2) {
            mes = "0" + mes;
        }
        if (dia.length() < 2) {
            dia = "0" + dia;
        }
        return "'" + año + "-" + mes + "-" + dia + "'";
    }
       public void cargarCombo() {
        cmbdia.removeAllItems();
        cmbaño.removeAllItems();
        cmbmes.setSelectedIndex(0);
        for (int i = year; i >= 1950; i--) {
            cmbaño.addItem(String.valueOf(i));
        }

        for (int i = 1; i < 32; i++) {
            cmbdia.addItem(String.valueOf(i));
        }
        sql.CamposCombo("select carreras from carreras", cmbcarrera);
        sql.CamposCombo("select estado_civil from estado_civil", cmbestadocivil);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JComboBox<String> cmbaño;
    private javax.swing.JComboBox<String> cmbcarrera;
    private javax.swing.JComboBox<String> cmbdia;
    private javax.swing.JComboBox<String> cmbestadocivil;
    private javax.swing.JComboBox<String> cmbmes;
    private javax.swing.JComboBox<String> cmbsexo;
    private javax.swing.ButtonGroup grupo_Seguro;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIMC;
    private javax.swing.JTextField txtNcuenta;
    private javax.swing.JTextField txtNidentida;
    private javax.swing.JTextField txtPA;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtPulso;
    private javax.swing.JTextField txtTalla;
    private javax.swing.JTextField txtTemperatura;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombreEm;
    private javax.swing.JTextField txtprocedencia;
    private javax.swing.JTextField txttelefono;
    private javax.swing.JTextField txttelefonoEm;
    // End of variables declaration//GEN-END:variables
}
